#!/usr/bin/with-contenv bash
#==============================================================================
# OpenThread BorderRouter web interface finish script
#==============================================================================
echo "INFO: otbr-web ended with exit code ${1} (signal ${2})..."
