#!/usr/bin/with-contenv bash
# ==============================================================================
# Start OpenThread BorderRouter web interface
# ==============================================================================
log 'info'  "Starting otbr-web..."
declare otbr_web_port

otbr_web_port="${OTBR_WEB_PORT:-8080}"

exec stdbuf -oL /usr/sbin/otbr-web -I wpan0 -d6 -s -p "${otbr_web_port}"
