#!/usr/bin/with-contenv bash
#==============================================================================
# mDNSResponder finish script
#==============================================================================
log 'info'  "mDNS ended with exit code ${1} (signal ${2})..."
